"""Create Game Model

Revision ID: 02dff235524c
Revises: 821562bf9765
Create Date: 2024-03-16 17:47:44.033047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02dff235524c'
down_revision = '821562bf9765'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
